version: '3.8'

services:
  web:
    build: .
    command: sh -c "python manage.py collectstatic --noinput && gunicorn mailing_list_management_service.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    expose:
      - "8000"
    environment:
      - STATIC_URL=/static/
      - STATIC_ROOT=/app/staticfiles
    depends_on:
      - db
      - redis
    env_file:
      - ./.env
    networks:
      - app_network

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./staticfiles:/app/staticfiles  # Локальная папка вместо volume
    depends_on:
      - web
    networks:
      - app_network

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    networks:
      - app_network

  redis:
    image: redis:7
    volumes:
      - redis_data:/data
    env_file:
      - ./.env
    networks:
      - app_network

volumes:
  postgres_data:
  redis_data:

networks:
  app_network:
    driver: bridge