# Generated by Django 5.2.1 on 2025-06-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(help_text='Введите email получателя рассылки', max_length=150, unique=True, verbose_name='Email')),
                ('fullname', models.CharField(help_text='Введите ФИО получателя рассылки', max_length=256, verbose_name='Фамилия Имя Отчество')),
                ('commentary', models.TextField(blank=True, help_text='Введите комментарий', null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Получатель рассылки',
                'verbose_name_plural': 'Получатели рассылки',
                'ordering': ['email', 'fullname'],
            },
        ),
    ]
