# Generated by Django 5.2.1 on 2025-06-01 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_subject', models.CharField(help_text='Введите тему письма', max_length=256, verbose_name='Тема письма')),
                ('email_body', models.TextField(help_text='Введите текст письма', verbose_name='Тело письма')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['email_subject'],
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_submission_time', models.DateTimeField(verbose_name='Дата и время первой отправки')),
                ('submission_time', models.DateTimeField(verbose_name='Дата и время окончания отправки')),
                ('status', models.CharField(choices=[('create', 'Создана'), ('start', 'Запущена'), ('end', 'Завершена')], default='create', max_length=6, verbose_name='Статус рассылки')),
                ('recipients', models.ManyToManyField(related_name='recipients', to='mail_management.mailrecipient')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='mail_management.message')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'ordering': ['message'],
            },
        ),
    ]
