# Generated by Django 5.2.1 on 2025-06-14 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mail_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailings', to=settings.AUTH_USER_MODEL, verbose_name='Создатель рассылки'),
        ),
        migrations.AddField(
            model_name='mailingattempt',
            name='mailing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='mail_management.mailing', verbose_name='Рассылка'),
        ),
        migrations.AddField(
            model_name='mailrecipient',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to=settings.AUTH_USER_MODEL, verbose_name='Владелец записи'),
        ),
        migrations.AddField(
            model_name='mailingattempt',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mail_management.mailrecipient', verbose_name='Получатель'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='recipients',
            field=models.ManyToManyField(related_name='mailings', to='mail_management.mailrecipient'),
        ),
        migrations.AddField(
            model_name='message',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL, verbose_name='Создатель сообщения'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailings', to='mail_management.message'),
        ),
        migrations.AddIndex(
            model_name='mailingattempt',
            index=models.Index(fields=['mailing'], name='mail_manage_mailing_ef2570_idx'),
        ),
        migrations.AddIndex(
            model_name='mailingattempt',
            index=models.Index(fields=['status'], name='mail_manage_status_9b2577_idx'),
        ),
        migrations.AddIndex(
            model_name='mailingattempt',
            index=models.Index(fields=['attempt_datetime'], name='mail_manage_attempt_e66239_idx'),
        ),
    ]
