# Generated by Django 5.2.1 on 2025-06-15 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_management', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ['message'], 'permissions': [('can_view_mailings', 'Can view mailings'), ('Can edit mailings', 'Can edit mailings')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AlterModelOptions(
            name='mailrecipient',
            options={'ordering': ['email', 'fullname'], 'permissions': [('can_view_recipients', 'Can view recipients'), ('can_edit_recipients', 'Can edit recipients')], 'verbose_name': 'Получатель рассылки', 'verbose_name_plural': 'Получатели рассылки'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['email_subject'], 'permissions': [('can_view_messages', 'Can view messages'), ('can_edit_messages', 'Can edit messages')], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
    ]
