# Generated by Django 5.2.1 on 2025-06-15 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_management', '0003_alter_mailing_options_alter_mailrecipient_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ['message'], 'permissions': [('can_view_mailings', 'Can view mailings'), ('can_edit_mailings', 'Can edit mailings'), ('can_disable_mailings', 'Can disable mailings')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
