# Generated by Django 5.2.1 on 2025-06-13 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_management', '0003_alter_mailing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно'), ('once', 'Один раз')], default='once', max_length=7, verbose_name='Периодичность'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='last_sent',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата последней отправки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailings', to='mail_management.message'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='recipients',
            field=models.ManyToManyField(related_name='mailings', to='mail_management.mailrecipient'),
        ),
        migrations.AlterField(
            model_name='mailrecipient',
            name='email',
            field=models.EmailField(help_text='Введите email получателя рассылки', max_length=150, unique=True, verbose_name='Email'),
        ),
    ]
