# Generated by Django 5.2.1 on 2025-06-13 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_management', '0004_mailing_frequency_mailing_last_sent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время попытки')),
                ('status', models.CharField(choices=[('success', 'Успешно'), ('failure', 'Не успешно')], max_length=7, verbose_name='Статус отправки рассылки')),
                ('mail_response', models.TextField(blank=True, null=True, verbose_name='Ответ почтового сервера')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='mail_management.mailing', verbose_name='Рассылка')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mail_management.mailrecipient', verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Попытка рассылки',
                'verbose_name_plural': 'Попытки рассылки',
                'ordering': ['-attempt_datetime'],
                'indexes': [models.Index(fields=['mailing'], name='mail_manage_mailing_ef2570_idx'), models.Index(fields=['status'], name='mail_manage_status_9b2577_idx'), models.Index(fields=['attempt_datetime'], name='mail_manage_attempt_e66239_idx')],
            },
        ),
    ]
