# Generated by Django 5.2.1 on 2025-06-15 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_management', '0004_alter_mailing_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ['message'], 'permissions': [('can_view_mailings', 'Can view mailings'), ('can_edit_mailings', 'Can edit mailings'), ('can_disable_mailings', 'Can disable mailings'), ('can_view_mailing_stat', 'Can view statistics of mailings')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
