# Generated by Django 5.2.1 on 2025-06-15 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_management', '0006_mailingattempt_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingattempt',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_mailings', to=settings.AUTH_USER_MODEL, verbose_name='Создатель попытки рассылки'),
        ),
    ]
