# Generated by Django 5.2.1 on 2025-06-15 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_management', '0007_alter_mailingattempt_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailingattempt',
            name='created_by',
        ),
    ]
