# Generated by Django 5.2.1 on 2025-06-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_management', '0008_remove_mailingattempt_created_by'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mailingattempt',
            name='mail_manage_mailing_ef2570_idx',
        ),
        migrations.RemoveIndex(
            model_name='mailingattempt',
            name='mail_manage_status_9b2577_idx',
        ),
        migrations.AddIndex(
            model_name='mailingattempt',
            index=models.Index(fields=['mailing', 'status'], name='mail_manage_mailing_2b54a7_idx'),
        ),
    ]
